version: '3.8'

services:
  suprasys-api-postgres:
    image: postgres
    container_name: suprasys-api-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: suprasys
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh:ro

volumes:
  pg_data:
    driver: local
